# Welcome to an Intro to Python

## Preamble:

This interactive notebook is part of a series which can be found here:
https://github.com/DimitriosAstro/Astronomy  
The notebook is distributed by Dimitrios Theodorakis under the GNU General Public License v3.0.

Find more info at www.w3schools.com, www.python.org, www.learnpython.org  
The Numpy section was adapted from work by Ridwan Barbhuiyan (https://github.com/rbarbhuiyan)

The purpose of this Notebook is to get you ready to explore the other Notebooks which each explore a topic in Astronomy and Astrophysics using the python programing language.

## Start:

*Shift+Enter* on a code snippet to run the code. Most of the time you'll have to run the snippets in order or you'll get an error.

If you're stuck you can consult the docs at https://docs.python.org/3/, and https://numpy.org/doc/stable/.  
You can also get advice from www.stackoverflow.com.

**Comments** - All code should be commented for readability

In [24]:
# This is a single line comment
'''This is a 
multiline comment'''

'This is a \nmultiline comment'

**Variables** - Assigning a variable. The dot says we want a float (decimal) not an integer. For b we assigned a string.

In [4]:
a = 2
a = 2.
b = "Hello World!"

**Printing** - Print a variable (or anything else) using the print() fucntion.

In [6]:
print(b)

Hello World!


**Maths** - Basic operators in python. Addition, subtraction, multiplication, division, and powers.

In [7]:
c = 2+2
d = 2-2
e = 2*2
f = 2/2
g = 2**2

**Print Text and Numbers** - Use str() to convert the number to a string first and join the two strings together.

In [8]:
print("My number is: "+str(c))

My number is: 4


**Lists** - A list of numbers or strings or anything else!

In [9]:
myList = [1,2,3,4,5]
print(myList)

[1, 2, 3, 4, 5]


Append to the list (at the end)

In [11]:
myList.append(6)
print(myList)

[1, 2, 3, 4, 5, 6, 6]


**Tuples** - These are like lists but cannot be changed once created.

In [12]:
myTuple = (1,2,3,4)
print(myTuple)

(1, 2, 3, 4)


**Indexing** - Access an element in a list/tuple using its index. The first element is at index 0. You can also use negative indices and select multiple elements at once using a slice.

In [13]:
print(myList[0])
print(myList[1])

print(myList[-1])
print(myList[-2])

print(myList[0:3])

1
2
6
6
[1, 2, 3]


**For Loops** - A for loop will do something (in this case print()) for each element (i) in the list/tuple.

In [14]:
for i in myList:
    print(i)

1
2
3
4
5
6
6


**Numpy Library** - A library is a set of pre-made functions that you can call on in your code.  
The Numpy library is a very useful maths library. We can import it using the code below. The *as np* means we can just write *np* after importing instead of the full name *numpy*.

In [15]:
import numpy as np

**Arrays** - A numpy array is generally faster than a list.

In [16]:
array1 = np.arange(1,11)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


**Dtypes** - Data types include int (integers), float (decimals), lists, tuples, and arrays.

In [17]:
print(type(array1))
# notice the difference between that and the type for myList
print(type(myList))

<class 'numpy.ndarray'>
<class 'list'>


**For Loop on Arrays**

In [18]:
for i in array1:
    print(i*2) # times each element by 2

2
4
6
8
10
12
14
16
18
20


**Maths on an Array** - Operations can be performed on each element of an array.

In [19]:
array2 = array1*2
print(array2)

[ 2  4  6  8 10 12 14 16 18 20]


**Linspace** - Another more controlled way of creating an array using a start, end, and number of points variables.

In [20]:
start = 0
finish = 5
step = 0.5
number = int((finish - start) / step) + 1

array3 = np.linspace(start, finish, number)
print(array3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


**2-D Arrays** - You can create 2-D arrays by specifying a shape. Normally we initialise an array using ones or zeros then change the values inside.

In [22]:
array4 = np.zeros((2,2))
array5 = np.ones((2,2))

print(array4)
print(array5)

# accessing a 2-D array [row, column], remember the first element is at index 0
print("-----")
print(array4[1,1])

# setting values in a 2-D array
print("-----")
array4[1,1] = 1
print(array4)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
-----
0.0
-----
[[0. 0.]
 [0. 1.]]


**Maths with Numpy** - Numpy has very useful maths functions. We can't list them all here but you can access the number pi and compute logs easily enough.

In [23]:
print(np.pi)
print(np.log(10))

3.141592653589793
2.302585092994046


## Over to You

**Task 1:** Create a list with your top 3 favourite foods. Print the list.  
**Task 2:** Print just your third favourite food.  
**Task 3:** Create an array using arange of the numbers 1-4. Print the square of those numbers.  
**Task 4:** Create a new 2-D array of zeros with size (3,3). Set the diagonals to 1 and print the array.

Solutions can be found in the non-interactive version of this document on the main repo (see very top).